"""date on BlogModel

Revision ID: c11d3fd323c9
Revises: 7a7994568c94
Create Date: 2022-05-02 21:28:31.937693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11d3fd323c9'
down_revision = '7a7994568c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'date')
    # ### end Alembic commands ###
